# Generated by Django 4.0.3 on 2022-04-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sxe',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
